In [1]:
#K.SAI CHANDANA REDDY
#BL.EN.U4CSE21083
#CSEB

In [2]:
#A1
# Importing required libraries
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
# Reading the dataset 
data = pd.read_csv('the_final_no_changes_data.csv')
# Selecting features X and target variable y
X = data[['polarity','subjectivity','len']]
y = data['category']
# Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Creating a svm classifier
clf = svm.SVC()
# Training the svm classifier on the training data
clf.fit(X_train, y_train)
# Getting the support vectors from the trained SVM model
support_vectors = clf.support_vectors_
#Printing the support vectors
print("Support Vectors:")
print(support_vectors)

Support Vectors:
[[ 1.07142857e-01  2.50000000e-01  1.10000000e+02]
 [ 0.00000000e+00  0.00000000e+00  1.26000000e+02]
 [-1.25000000e-01  2.50000000e-01  6.70000000e+01]
 ...
 [-2.00000000e-01  4.58333333e-01  1.33000000e+02]
 [-1.66666667e-01  3.33333333e-01  1.37000000e+02]
 [ 0.00000000e+00  1.00000000e+00  1.37000000e+02]]


In [3]:
#A2
# Importing  required libraries
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
# Reading the dataset 
data = pd.read_csv('the_final_no_changes_data.csv')
# Select features X and target variable y from the dataset
X = data[['polarity', 'subjectivity', 'len']]
y = data['category']
# Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Creating a Support Vector Machine classifier
clf = svm.SVC()
# Training the SVM classifier on the training data
clf.fit(X_train, y_train)
# Calculating accuracy on the test set
accuracy = clf.score(X_test, y_test)
print(f"Accuracy on the test set: {accuracy:.2f}")
# Example  of a test vector
test_vector = [0, 0.8, 10]
# Making predictions for the test vector
predicted_class = clf.predict([test_vector])[0]
print(f"Predicted class for the test vector: {predicted_class}")


Accuracy on the test set: 0.05
Predicted class for the test vector: 32


C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [4]:
#A3
# Predicting labels on the test set
predicted_labels = clf.predict(X_test)
#Iterating through each data point 
for i in range(len(y_test)):
    actual_class = y_test.iloc[i]
    predicted_class = predicted_labels[i]
    print(f"Actual Class: {actual_class}, Predicted Class: {predicted_class}")
# Setting a threshold
threshold = 5
# Counting correct predictions based on defined threshold
correct_predictions = 0
for actual, predicted in zip(y_test, predicted_labels):
    if abs(actual - predicted) <= threshold:
        correct_predictions += 1
# Calculating and print accuracy based on defined logic
accuracy = correct_predictions / len(y_test)
print(f"Accuracy based on  logic (threshold={threshold}): {accuracy:.2f}")


Actual Class: 26, Predicted Class: 32
Actual Class: 34, Predicted Class: 41
Actual Class: 35, Predicted Class: 39
Actual Class: 16, Predicted Class: 36
Actual Class: 9, Predicted Class: 41
Actual Class: 29, Predicted Class: 32
Actual Class: 5, Predicted Class: 41
Actual Class: 6, Predicted Class: 32
Actual Class: 1, Predicted Class: 9
Actual Class: 10, Predicted Class: 0
Actual Class: 9, Predicted Class: 9
Actual Class: 12, Predicted Class: 31
Actual Class: 23, Predicted Class: 38
Actual Class: 3, Predicted Class: 0
Actual Class: 14, Predicted Class: 39
Actual Class: 36, Predicted Class: 31
Actual Class: 31, Predicted Class: 41
Actual Class: 16, Predicted Class: 0
Actual Class: 19, Predicted Class: 31
Actual Class: 4, Predicted Class: 41
Actual Class: 9, Predicted Class: 9
Actual Class: 30, Predicted Class: 0
Actual Class: 39, Predicted Class: 39
Actual Class: 32, Predicted Class: 31
Actual Class: 30, Predicted Class: 9
Actual Class: 22, Predicted Class: 32
Actual Class: 6, Predicted C

In [19]:
#A4
#Importing neccesary libraries
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
kernel_functions = ['linear', 'poly', 'rbf', 'sigmoid']
for kernel in kernel_functions:
    # Creating an SVM classifier with the current kernel function
    clf = svm.SVC(kernel=kernel)
    # Fit the classifier to the training data
    clf.fit(X_train, y_train)
    # Use the classifier to make predictions on the test set
    y_pred = clf.predict(X_test)
    # Calculating and print accuracy for the current kernel
    accuracy = accuracy_score(y_test, y_pred)
    print(f"Accuracy with '{kernel}' kernel: {accuracy:.2f}")


Accuracy with 'linear' kernel: 0.60
Accuracy with 'poly' kernel: 0.83
Accuracy with 'rbf' kernel: 0.69
Accuracy with 'sigmoid' kernel: 0.60
